### ISSUE TITLE
no big deal

### ISSUE THREAD

**Issue by imrenagi** [cloudnative-id/announcer-system#4]
variable name in golang usually uses camel case and start with lower letter.

```
var foo string
```
not 
```
var Foo string
```

also parameter name should also be a camel case.

```
func delay(duration time.Time) {
}
```
not 
```
func delay(Duration time.Time) {
}
```

**Comment by zufardhiyaulhaq** [comment]
:)) currently I am following the right picture, lol
![image](https://user-images.githubusercontent.com/11990726/72350694-81361b80-3711-11ea-8ce7-d1e65198ad30.png)
